{"id":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","dependencies":[{"name":"D:\\JavaScript\\complete-javascript-course-master\\complete-javascript-course-master\\18-forkify\\starter\\package.json","includedInParent":true,"mtime":1710601249156},{"name":"D:\\JavaScript\\complete-javascript-course-master\\complete-javascript-course-master\\18-forkify\\starter\\node_modules\\core-js\\package.json","includedInParent":true,"mtime":1710601242175},{"name":"../internals/an-object","loc":{"line":2,"column":23,"index":38},"parent":"D:\\JavaScript\\complete-javascript-course-master\\complete-javascript-course-master\\18-forkify\\starter\\node_modules\\core-js\\internals\\call-with-safe-iteration-closing.js","resolved":"D:\\JavaScript\\complete-javascript-course-master\\complete-javascript-course-master\\18-forkify\\starter\\node_modules\\core-js\\internals\\an-object.js"},{"name":"../internals/iterator-close","loc":{"line":3,"column":28,"index":94},"parent":"D:\\JavaScript\\complete-javascript-course-master\\complete-javascript-course-master\\18-forkify\\starter\\node_modules\\core-js\\internals\\call-with-safe-iteration-closing.js","resolved":"D:\\JavaScript\\complete-javascript-course-master\\complete-javascript-course-master\\18-forkify\\starter\\node_modules\\core-js\\internals\\iterator-close.js"}],"generated":{"js":"'use strict';\r\nvar anObject = require('../internals/an-object');\r\nvar iteratorClose = require('../internals/iterator-close');\r\n\r\n// call something on iterator step with safe closing on error\r\nmodule.exports = function (iterator, fn, value, ENTRIES) {\r\n  try {\r\n    return ENTRIES ? fn(anObject(value)[0], value[1]) : fn(value);\r\n  } catch (error) {\r\n    iteratorClose(iterator, 'throw', error);\r\n  }\r\n};\r\n"},"sourceMaps":{"js":{"mappings":[{"source":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","original":{"line":1,"column":0},"generated":{"line":1,"column":0}},{"source":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","original":{"line":2,"column":0},"generated":{"line":2,"column":0}},{"source":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","original":{"line":3,"column":0},"generated":{"line":3,"column":0}},{"source":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","original":{"line":4,"column":0},"generated":{"line":4,"column":0}},{"source":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","original":{"line":5,"column":0},"generated":{"line":5,"column":0}},{"source":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","original":{"line":6,"column":0},"generated":{"line":6,"column":0}},{"source":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","original":{"line":7,"column":0},"generated":{"line":7,"column":0}},{"source":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","original":{"line":8,"column":0},"generated":{"line":8,"column":0}},{"source":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","original":{"line":9,"column":0},"generated":{"line":9,"column":0}},{"source":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","original":{"line":10,"column":0},"generated":{"line":10,"column":0}},{"source":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","original":{"line":11,"column":0},"generated":{"line":11,"column":0}},{"source":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","original":{"line":12,"column":0},"generated":{"line":12,"column":0}},{"source":"node_modules/core-js/internals/call-with-safe-iteration-closing.js","original":{"line":13,"column":0},"generated":{"line":13,"column":0}}],"sources":{"node_modules/core-js/internals/call-with-safe-iteration-closing.js":"'use strict';\r\nvar anObject = require('../internals/an-object');\r\nvar iteratorClose = require('../internals/iterator-close');\r\n\r\n// call something on iterator step with safe closing on error\r\nmodule.exports = function (iterator, fn, value, ENTRIES) {\r\n  try {\r\n    return ENTRIES ? fn(anObject(value)[0], value[1]) : fn(value);\r\n  } catch (error) {\r\n    iteratorClose(iterator, 'throw', error);\r\n  }\r\n};\r\n"},"lineCount":13}},"error":null,"hash":"b50a61cef65fd5fb0e515bc89af56819","cacheData":{"env":{}}}